= Duo Lingo notebook: Some sentences that attracted my attention
Bob McColly (C) 2018 Heart of Diamond GmbH
Version 0.1, 15.12.2018
// Set Attributes
:sectnums:
:toc: left
:toclevels: 4
:toc-title: Contents
:experimental:
:description: Digital version of ESET NOTEBOOK
:keywords: English duo lingo
:icons: font
:source-highlighter: coderay
// rouge coderay highlights prettify pigments
:show-link-uri:

// If the entire sentence is parenthetical, then you put the punctuation inside
// the parenthesis.

This is a digital copy of a handwritten notebook.
It contains some sentences which I'd like to be fluent of.


== Free topic
It happened _like this_...

She is talking to _the_ dog.

I went up. (Я шел наверх.)

I _listen to_ the music.

I will _get used_ to it.

Put a _trash bag_ inside a bin, please.

The exit is _to the right_.

I am ready _for_ the consequences.

He is afraid of his shadow.

I was thinking the same thing.

What does she feel? (Что она чувствует?)

Who is _coming_ with me? (Кто идет со мной?)

You have a few books. (У тебя мало книг.)

He is sleeping _on_ a chair.

This method offers two advantages.

Four is two times two.

Speak slowly and clearly.

From far away.

Do it another time!

He is _a_ great person.

I believe in luck. Wish me luck!

I _want you_ to open your eyes.

Let us go together _to_ a concert.

I fail to remember her name.

I am _getting off_ *at* the next station.

When will the delivery arrive?

We gotta get out of here.

I do not like his actions.

We need _to take_ action. (Нам надо действовать.)

I am _getting up_! (Я встаю!)

She speaks to herself

We like expressions of love.

It is necessary to choose.

----
- Did they get it?
- No.
- Have you got it?
- No.
----

She does not have _a_ personality.

When does it close? (Когда оно закрывается?)

The conversation is over!

My day was full of surprises.

There is no doubt.

Why *are* you always late? (_late_ - adj.)

I work _on_ the engine. (Я работаю над этим двигателем.)

I am no longer a King Of The Hill.

She reached her objective. (Она достигла своей цели.)

My daughter wishes for a horse. (Моя дочь желает лошадь.)

----
- You okay?
- Never better. It's just another day in a fleet.
----

Take what he offers.

There was a very famous battle _here_.

We went to my house.

I _went up_. (Я шел наверх.)

I do not have _any_ doubts.

That building is an important symbol.

They are making a mistake again.

It was a total failure.

I have to feel it. (Я должен почувствовать это.)

It is a matter of time.

I am little tired that's it.

They came with me. (Они пришли со мной.)

He wishes me well. (Он желает мне добра.)

The door opens to the inside.

Do not look _at_ me!

Did something happen? (Что-то случилось?)

She _felt_ well. (Она чувствовала себя хорошо.)

They never pay any attention _to_ me.

Where is the entrance to the museum?

He is a student currently still living with his parents.

He is a man of action.

Now and then. (Время от времени.)

We have an appointment with him tomorrow.

_The time_ will come when you will be sorry for it.

*Hope* is not a strategy.

Find a convenient moment.

Here are your keys.

He usually goes to the park with his dog.

During my youth.

She _does not_ affect me.

Which _one_ is my screen?

I am not tired _at all_.

Where _is_ everybody else?

I _made_ my decision.

What _did_ you do there?

What _did_ you do today?

We didn't show them our new flat.

Did you have a good time _on the sea side_?

Hi _did not_ talk to me. (Он не разговаривал со мной.)

Fine. No complaints.

It's a longtime since I saw you _last_.

She searches them. (Она обыскивает их.)

To search the house. (Обыскать дом.)

To search for the house. (Искать дом.)

He _took a look_ at the watch.

I will _take a look_. (Я посмотрю.)

Beware of vicious dogs!

[subs=+quotes]
// The "quotes" substitution enables inline formatting.
----
- _No way_. You're not leaving.
- Really? And what _makes_ you think you can tell me what to do?
- See? We need you. You may be a huge pain in _the_ ass, but you're smart.
----

Do not _ever_ call me again!

He does _the_ opposite of what he has to do.

He is always *won* _on account_ of been able to predict
the situation correctly.

I will _get_ a dog.

I will _get used to_ it.

I never go anywhere.

== Time

Eighteen minutes latter, the battle was over.

== Photography
I really like to _take pictures_ of _the_ sunset from my window.

I like photography.

== Study

I need to learn.

How are your _studies_ going?

You'll be looking at somewhere around fifteen thousand US dollars per semester.

She was _taking_ the girl to school by car.

She walks to school. (Она ходит в школу пешком.)

== Transportation
I am getting off _at_ the next station.

== Clothes
She _puts_ her coat on.

She _gets_ dressed.

She _puts on_ her cloths.


== Movies

I was sad after the film.

== Sport & Health

There is no risk to health.

He exercises every day.

I am _taking care_ of my health.

I believe more in _the_ diet than in drugs.

She felt well. (Она чувствовала _себя_ хорошо.)

I left my tennis racket _on_ the train.

You look rested and refreshed.

[subs=+quotes]
----
- His brother in low is ill.
- What disease does he have?
- He is _very ill_ and he needs a lot of care.
----

He warmly congratulated me *on* my first place.

=== Running
Doctors agree that running is good for health.

I neither walk nor run.

We run _through_ the fields. (Мы бежим по полям.)

At what speed does he run?

I run _on_ Thursdays.

=== Walking

I want to go _for_ a walk.

He _goes_ for a walk with his dog every morning.

I am _walking by_ your house.

A map of the city always helps.

=== Medicine

I have a weak sight.

He drank to forget the pain.

The brain is in the head.

I had an accident on the *job*.

I think I took good care of it. ( Я думаю я об этом хорошо позаботился.)

My back is _in pain_.


== Weather
It _kept on_ raining for a week.

Lets go out now. _It_ isn't raining any more.

I think _it_ is going to rain today.

I think _it will_ rain today.

I do not know if _it_ is going to rain tomorrow.

_It_ may rain this afternoon.

It has stopped _raining_.

It is _raining_ again.

_In_ November there is rain. (В ноябре - дождь.)

Yes, it rains.

Is it _still_ raining?

It rained all day. (Дождь шел весь день.)

== Excuses
Can I be excused? Nature calls...

Excuse me, I have to use the facilities.

== Food

A fork _fell off_ the table.

_Have_ you _ordered_ lunch yet? (Вы уже заказали обед?)

I recently ate chicken.

The price of dinner is not including the wine.

Do you start _the_ morning with coffee?

Sometimes we eat fish _for_ dinner.

Are they going to drink?

I did not use to drink beer.

[verse]
____
- Hey, Julie, you want to go grab something to eat?
- Sure!
- What do you _feel like having_?
- I really _feel like having_ a big juicy steak!
____


== Family
We _raise_ our children.

He _looks a lot_ like you.

Do they _come_ from a musical family?

My children have such different personalities.

There is enough room here for my family.

== Internet
We live in the age of technology.

You do not have access to the Internet.

What are we doing _on_ the Internet?

What do we do on the Internet?

I think the message has _a virus_.

He is always _on_ *the* Internet.

They found it by searching online.

== Money

The dollar is a type of currency.

How much _does_ the meat cost?

I want to know how much it costs.

How much _is_ my coat _worth_?

Can I pay by credit card?

Pay attention _to_ your wallet!

How much do you ask for this?

What do I _get out_ of it?

== Toast
Here's to being invincible!

To your health!

== Job
He is an able man. (Он способный человек.)

_This advantage_ helps me _in_ my job.

[subs=+quotes]
----
The bank I work _for_ isn't doing so well this year.
Things are not so good at work.
The company is loosing money.
The situation is already bad and _it is getting_ worse.
I am thinking of _giving up_ my job.
I need (he needs) _to look for_ a job.
----

Do you have work experience?

What is _the_ relation between work and school?

Do you have professional experience?

He works in a bank.

He offers me to work with him.

_Take_ what he offers.

His work continues.

I had to find myself again. (Я должен был найти себя снова.)

It is a good start but we still have a lot of work to do.

I need to look for a job.

== Subordination

Excuse me, commander. Will you have a minute of your time?

== Greetings

[verse]
____
Hey (Hi! Hello!), Helen! ^casual^

Morning, guys! ^gender_neutral^

Hey, how are you? Good, how are you?
It's good to see you! How have you been?

Seeing you _makes_ me happy.

Hey, Scooter. What's up?
Hey, how's it going?

What's up?
Not much. What's up with you?

Hey, Johnny, Teela! How you guys are doing today?
Good. How are you?

Hey, what's going on?
Not much. How are you?
I'm just hanging out. I hear it's your birthday today.
It is, actually.
Happy birthday, Rachel!
Thank you!

Hey, how are you doing?
I'm not bad, thanks. What about you?

How are you doing today?
I'm pretty good (I'm all right.) How about you? What's news?

How are you?
Fabulous.
As always!

Hey, Aaron!
Hey, how are you doing?
Good, how are you?
OK!
____

With whom do I have _the_ honor of speaking?

Let me introduce you to my wife.

It is a pleasure to meet all of you.

== Goodbye
OK, see you next time! Bye!

See you soon.

Have a nice day!

Until next week.

See you later, bay.
See you soon (pronounced `ya`), bay!

== Responses to Thanks
https://www.idioms.online/dont-mention-it/[Idioms Online]

Thanks for your efforts.

I am taking off my hat.

[verse]
____
- Thank you.
- You're welcome.

- Thank you very much.
- I do very little. (Do little.)

- Thanks for helping me move all that junk.
- Don’t even mention it, but I could use a beer!

- I appreciate your help in this matter.
- Not at all. (Your thanks are not needed at all. I was glad to do it.)

- Thanks of writing that letter of recommendation, Mr. Foster."
- My pleasure. (The pleasure was all mine.)

- Thanks so much!
- It was my pleasure.

- Thanks for lending me that ten dollars.
- No problem. (No trouble. It was no trouble at all.) ^lack_warmth^

- Thanks for picking me up for work.
- No sweat. (It's no sweat) ^very_informal^

- Thanks so much for helping me!
- Forget it. (Forget it, not at all.) ^sounds_rude^

- Thanks for your help earlier.
- Sure. ^sounds_terse_and_detached^ *Terse* - abrupt and unfriendly.
  (Sure, no problem. Sure, don't mention it. Sure, my pleasure.)

- Thanks a million for fixing my car again.
- Sure, no problem at all.

- Thank you very much! (some one is being too apologetic for having troubled you)
- That's all right. (It's all right. That's OK. It's OK) ^very_informal^
____

== Useful Telephone Phrases
He is talking on the telephone.

=== Making Contact
I'd like to speak to ...

I'm calling from ...

I'm calling on behalf of ...

=== Taking a call
How can I help you?

Where are you calling from?

He is talking on the phone.

== Perfect

I have been waiting for you.

By then, they had already led the children. (К тому времени они уже привели этих
детей.)

The time has finally come.

I _already have drunk_ a cup of tea at home.

He _had just eaten_. (Он только что поел.)

She _has lost_ her phone.

She _had known_ him last month. (Она уже знала его в прошлом месяце.)

We _have had_ a lot of problems.

Have you written this number?

He has been sleeping like a baby.

We have never been friends.

Where _has_ she been? (Где она была?)

He sleeps after he has drunk. (Он спит после того как он выпил.)

You have never cooked soup for me.

Have you ever drunk coffee before?

No one _has ever called_ me *that*.

It was a name that I had never heard before.

What _have you brought_ *us*?

To _have been able_. (Суметь.)
To _be_ able. (Уметь.)

Have you understood, haven't you?

Have you been _to_ his house? (Ты был в его доме?)

Where have you been?

As we thought, she _had gone_ abroad.

He _had not_ *known* what to do. (Он еще не знал что делать.)

I _have come_ to speak with you. (Я пришел поговорить с тобой.)

She _has taken_ a green apple.

He _has felt_ tired. (Он почувствовал себя усталым.)

The plane _had already taken off_ when I _reached_ the airport.

He has told me. (Он рассказал мне.)

He has changed. (Он изменился.)



== ING
Can't help doing. (Ничего не могу с собой поделать чтобы...)

Couldn't help drinking. (Не мог не выпить.)

End up + VERB-ING (Закончите тем что будете...)

== Confusing English

_I will_ then add them here. (Я тогда добавлю их сюда.)

I _feel like seeing_ the city.

We are going to read more books than *him*.

Is *there* a telephone *here*?

The _boyfriend_ and _girlfriend_ walked along the beach. (Парень и девушка
гуляли вдоль пляжа.)

Is *there* a zoo in the city?

What did you want to talk to me about?

_These_ pants are _in style_. (Эти брюки в моде.)

She wants him to tell her the truth.

== Proverbs
Beware the fury of a patient one.

Sammy loves apple pies even more than his wife Sally.

Analysis - paralysis. Go for it!

Respect is not free.

I _feel like_ seeing the city. (Мне хочется увидеть этот город.)

== Human descriptions
My wife cooks well.

== Tables
|===
|Will we be allowed to come to this party? | We will be allowed to come to this
party. | We won't be allowed to come to this party.
|May we come to his party? | We may come to this party. | We may not come to his
party.
|Might we come to his party? | We might come to his party | We might not come to
his party.
|===

|===
|Will you be able to help me? | You will be able to help me. | You won't be able
to help me.
|Can you help me? | You can help me. | You can't help me.
|Could you help me? | You could help me (I was able to ...) | You couldn't help
me
|===

|===
|Will I have to work hard? | He will have to work hard. | He won't have to work
hard.
|Must he work hard? | He must work hard. | He mustn't work hard.
|Did he have to work hard? | He had to work hard. | He didn't have to work hard.
|===

== Cites

.In magic, man has to rely on himself
[#magic,money,superpower]
[quote, J.K. Rowling, An interview about "Harry Potter" books]
____
In magic man has to rely on himself so in religion of course you're looking for outside support.
That's the perennial (everlasting, perpetual, annual) appeal of magic, the idea that we ourselves
have power and we can shape our world.

I sometimes think it's very analogous to having a lot of money,
that people think because that's kind of like a superpower.
I've often thought this since all this happened to me,
people think that well, you can solve anything now.
Yeah, really? It doesn't work like that! ...
____


.Not have lived at all
[#cautiousness]
[quote, J.K. Rowling, An interview about "Harry Potter" books]
____
It is impossible to live without failing at something unless you
live so cautiously that you might as well not have lived at all.
____

.IT guy.
[#guy]
[quote, Jeremy Cioara, ICND1.[26/38]26 - Routing - Implementing - Static Routing - 00:01:15]
____
If some one would ask me a question: "Jeremy, what do you do?", I would respond
and I'd say "I'm an IT guy: that's what I do." Is that a complete answer? No!
____


.If you are constantly in the state of satisfaction and happiness
[#happiness]
[quote, Jordan Peterson, MOST EPIC SPEECH - (Video Edit)]
____
Some people will tell you that purpose of the life is to be
happy. Happiness is something that is *done in* by the first harsh
blow that reality deals you.

There are many circumstances in life where
happiness is not only the wrong response, but also where the expectation of
happiness as a response will put you absolutely the wrong psychological state to
be prepared for what must be done.

People are built, so to speak, to experience
a very wide range of motivational and emotional states. So, there is a time to
be compassionate, and there is a time to be aggressive, and there is a time to be
in pain, and there's a time go be anxious, and there's a time to be joyous, and
the time to be satisfied. The healthy and well adopted person has a very wide
range of finally differentiated responses which cannot be boiled down to a
single dimension, say _happiness_ vs _unhappiness_.

Life is not that simple, life is
complex and tragic and difficult. The problem with the public portrayal of the
ideal state of human as the happiness is that it makes all of these people feel
ashamed of their own suffering. They feel that if they are suffering and if they
find their life tragic in its essence than that means that there is something wrong
with them. And instantly that makes it impossible for them to communicate
anything real about their own tragedy.

If you are constantly in the state of
satisfaction and happiness then nothing is going to affect you deeply enough.
So that you'll become deep, and life without depth is by definition shallow and
meaningless, because what it does is broaden and deepen your life in a manner
that you might compare to the difference between elevator music and a
Beethoven symphony. It's not that the symphony is in any sense happier than the
*muzak*, in fact quite a contrary, but it's deeper and more profound, and richer,
and incorporates more, and justifies itself more.

And that's the right metaphor
for life, not happiness, but depth and differentiated quality, profundity to
match the profundity and the necessity of suffering.

*Source*: https://youtu.be/eCC3-JI8cKk[Jordan Peterson's MOST EPIC SPEECH - (Video Edit) on YouTube]
____
